<a href="https://colab.research.google.com/github/songqsh/foo1/blob/master/src/autograd01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Higher order derivatives with pytorch

In [0]:
import torch
import torch.nn as nn
from torch.autograd import grad

## The derivatives of 1-1 mapping



In [3]:
#The 1-1 mapping to take derivative

#f = lambda x: x**3 + 2*x
net = nn.Linear(1, 1)
for p in net.parameters():
  print(p)

f = lambda x: net(x) + x**2

Parameter containing:
tensor([[0.0168]], requires_grad=True)
Parameter containing:
tensor([-0.7037], requires_grad=True)


### At a point

In [8]:
#At one point
x = torch.tensor([2], dtype=torch.float, requires_grad=True)
y = f(x) #function value
print('y', y)

y_g1 = grad(y, x, create_graph=True)[0] #first order
print('y_g1', y_g1)

y_g2 = grad(y_g1, x, create_graph=True)[0] #second order
print('y_g2', y_g2)


y tensor([3.3299], grad_fn=<AddBackward0>)
y_g1 tensor([4.0168], grad_fn=<AddBackward0>)
y_g2 tensor([2.], grad_fn=<MulBackward0>)


### At an array

In [9]:
#At an array
x_arr = torch.tensor([1, 2], dtype=torch.float, requires_grad=True).reshape(2,1)
for x in x_arr:
  y = f(x) #function value
  print('y', y) 

  y_g1 = grad(y, x, create_graph=True)[0] #first order
  print('y_g1', y_g1)
  
  y_g2 = grad(y_g1, x, create_graph=True)[0] #second order
  print('y_g2', y_g2)

y tensor([0.3131], grad_fn=<AddBackward0>)
y_g1 tensor([2.0168], grad_fn=<AddBackward0>)
y_g2 tensor([2.], grad_fn=<MulBackward0>)
y tensor([3.3299], grad_fn=<AddBackward0>)
y_g1 tensor([4.0168], grad_fn=<AddBackward0>)
y_g2 tensor([2.], grad_fn=<MulBackward0>)


# The derivatives of 2-1 mapping

In [5]:
#The 2-1 mapping to take derivative

net = nn.Linear(2, 1)
for p in net.parameters():
  print(p)

f = lambda x: net(x) + torch.sum(x**3)

Parameter containing:
tensor([[-0.5842,  0.5356]], requires_grad=True)
Parameter containing:
tensor([-0.6364], requires_grad=True)


### At a point

In [6]:
x = torch.tensor([0,1], dtype=torch.float, requires_grad=True)
y = f(x) #function value
print('y', y)

y_g1 = grad(y, x, create_graph=True)[0] #gradient
print('y_g1', y_g1)

y_g2_0 = grad(y_g1[0], x, create_graph=True, allow_unused=True)[0] #Hessian line-0
print('y_g2_0', y_g2_0)


y_g2_1 = grad(y_g1[1], x, create_graph=True, allow_unused=True)[0] #Hessian line-1
print('y_g2_1', y_g2_1)

y tensor([0.8992], grad_fn=<AddBackward0>)
y_g1 tensor([-0.5842,  3.5356], grad_fn=<AddBackward0>)
y_g2_0 tensor([0., 0.], grad_fn=<MulBackward0>)
y_g2_1 tensor([0., 6.], grad_fn=<MulBackward0>)
