<a href="https://colab.research.google.com/github/songqsh/foo1/blob/master/src/bfs_gw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BFS



In [2]:
# import packages
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)
import itertools

In [10]:
A = np.array([[2., 1., 1, 0, 0], [1.,1,0,1, 0], [1., 0, 0, 0, 1]])
b = np.array([100.,80,40])
c = np.array([3,2,0., 0, 0])
m, n = A.shape
print(f'coefficient matrix is \n {A}')
print(f'right hand side vector is \n {b}')
print(f'coefficient of objective function is \n {c}')
print(f'n is {n} and m is {m}')

coefficient matrix is 
 [[2. 1. 1. 0. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]
right hand side vector is 
 [100.  80.  40.]
coefficient of objective function is 
 [3. 2. 0. 0. 0.]
n is 5 and m is 3


In [26]:
a_list = list(range(n))

bv_list = itertools.combinations(a_list,m)

for bv in bv_list:
  try:
    bs = la.solve(A[:,bv], b)
    print(f'bv is {bv} and bs is {bs}')
    if min(bs) >= 0:
      z=0
      for i in range(m):
        z = z + c[bv[i]]*bs[i]
      print(f'...it is bfs and z-value is {z}')

  except:
    print(f'bv is {bv} and it is singular')


bv is (0, 1, 2) and bs is [ 40.  40. -20.]
bv is (0, 1, 3) and bs is [40. 20. 20.]
...it is bfs and z-value is 160.0
bv is (0, 1, 4) and bs is [20. 60. 20.]
...it is bfs and z-value is 180.0
bv is (0, 2, 3) and bs is [40. 20. 40.]
...it is bfs and z-value is 120.0
bv is (0, 2, 4) and bs is [ 80. -60. -40.]
bv is (0, 3, 4) and bs is [ 50.  30. -10.]
bv is (1, 2, 3) and it is singular
bv is (1, 2, 4) and bs is [80. 20. 40.]
...it is bfs and z-value is 160.0
bv is (1, 3, 4) and bs is [100. -20.  40.]
bv is (2, 3, 4) and bs is [100.  80.  40.]
...it is bfs and z-value is 0.0


In [19]:
bs

array([100.,  80.,  40.])

In [20]:
bv

(2, 3, 4)

0 2 100.0 0.0
1 3 80.0 0.0
2 4 40.0 0.0
0.0


In [23]:
c

array([3., 2., 0., 0., 0.])