# BFS



In [33]:
# import packages
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)
import itertools

In [34]:
# setup
A = np.array([[2., 1., 1, 0, 0], [1.,1,0,1, 0], [1., 0, 0, 0, 1]])
b = np.array([100.,80,40])
c = np.array([3,2,0., 0, 0])
m, n = A.shape
print(f'coefficient matrix is \n {A}')
print(f'right hand side vector is \n {b}')
print(f'coefficient of objective function is \n {c}')
print(f'n is {n} and m is {m}')

coefficient matrix is 
 [[2. 1. 1. 0. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]
right hand side vector is 
 [100.  80.  40.]
coefficient of objective function is 
 [3. 2. 0. 0. 0.]
n is 5 and m is 3


In [35]:
bv_list = itertools.combinations(range(n),m)
counter = 0
for bv in bv_list:
  try:
    print(f'inspecting basic variables with indices {bv} ...')
    bs = la.solve(A[:,bv], b)
    # print(f'...bs is {bs}')
    if min(bs) >= 0:
      counter = counter + 1
      z=0
      for i in range(m):
        z = z + c[bv[i]]*bs[i]

      print(f'...it is feasible with bfs {bs} and z-value is {z}')

  except la.LinAlgError as err:
    print(f'...{err}')
    pass

print(f'number of feasible solution is {counter}')

inspecting basic variables with indices (0, 1, 2) ...
inspecting basic variables with indices (0, 1, 3) ...
...it is feasible with bfs [40. 20. 20.] and z-value is 160.0
inspecting basic variables with indices (0, 1, 4) ...
...it is feasible with bfs [20. 60. 20.] and z-value is 180.0
inspecting basic variables with indices (0, 2, 3) ...
...it is feasible with bfs [40. 20. 40.] and z-value is 120.0
inspecting basic variables with indices (0, 2, 4) ...
inspecting basic variables with indices (0, 3, 4) ...
inspecting basic variables with indices (1, 2, 3) ...
...Singular matrix
inspecting basic variables with indices (1, 2, 4) ...
...it is feasible with bfs [80. 20. 40.] and z-value is 160.0
inspecting basic variables with indices (1, 3, 4) ...
inspecting basic variables with indices (2, 3, 4) ...
...it is feasible with bfs [100.  80.  40.] and z-value is 0.0
number of feasible solution is 5
