## Pivoting

Pivoting with $(i,j)$-entry means converting the matrix by multiple EROS so that the resulting matrix has all zeros in $j$-column,but one in $(i,j)$-entry. This is the key step in updating basic feasible solution. Pivoting is essential for solving linear systems and linear programmings. We consider the following linear system by pivoting as an example:
$$
x_1 + 2 x_2 - x_3  = 4$$
$$- x_1 - x_2 + 2x_3  = 1$$
$$x_1 \quad \quad \quad + x_3  = 6$$


In [4]:
import numpy as np
from simplex import pivoting
# initial matrix input
M = np.array([[1,2,-1,4.],[-1.,-1, 2,1], [1.,0,1, 6]])
print(f'============================')
print(f'initial augmented matrix is \n {M}')
pivoting(M,0,0)
pivoting(M,1,1)
pivoting(M,2,2)
print(f'============================')
print(f'matrix after pivoting is \n {M}')

initial augmented matrix is 
 [[1.00 2.00 -1.00 4.00]
 [-1.00 -1.00 2.00 1.00]
 [1.00 0.00 1.00 6.00]]
matrix after pivoting is 
 [[1.00 0.00 0.00 3.00]
 [0.00 1.00 0.00 2.00]
 [0.00 0.00 1.00 3.00]]
