# Simplex method

We are going to illustrate simplex tableau method for the dual of the diet problem:
$$\max z = 500 x_1 + 6x_2 + 10 + 8 x_4$$
s.t.
$$\begin{array}{ll}
400 x_1 + 3x_2+2x_3+2x_4 & \le 50\\
200 x_1 + 2x_2 + 2x_3 + 4x_4 & \le 20\\
150x_1 \quad \quad \quad + 4x_3 + x_4 & \le 30\\
500x_1 \quad \quad \quad + 4x_3 + 5x_4 & \le 80 \\
x_1, x_2, x_3, x_4\ge 0.
\end{array}
$$

In [21]:
# import package
import numpy as np

float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

## Pivoting

Pivoting with $(i,j)$-entry means converting the matrix by multiple EROS so that the resulting matrix has all zeros in $j$-column, but one in $(i,j)$-entry. This is the key step in updating basic feasible solution.

In [22]:
#pivotize with (i,j)
def pivot(a_mat, i_row, j_col):
  a_mat[i_row] = a_mat[i_row]/a_mat[i_row,j_col] #scale to get one in (i,j)
  n_rows, _ = a_mat.shape
  for k in range(n_rows):
    if k==i_row:
      continue # skip i-row
    a_mat[k] = a_mat[k] - a_mat[i]*a_mat[k,j_col] # replacement to get zero
    

## Initial tableau

In [23]:
A = np.array([[1, -500, -6, -10, -8, 0, 0, 0, 0, 0],
              [0., 400., 3., 2., 2., 1., 0, 0., 0, 50.],
              [0, 200, 2., 2., 4., 0, 1, 0, 0, 20.],
              [0., 150, 0, 4, 1, 0, 0, 1, 0, 30.],
              [0, 500, 0, 4, 5, 0, 0, 0, 1, 80]
              ])
n_row, n_col = A.shape

print('tableau has ' + str(n_row) + ' rows and ' + str(n_col) + ' columns')
print(A)

tableau has 5 rows and 10 columns
[[1.00 -500.00 -6.00 -10.00 -8.00 0.00 0.00 0.00 0.00 0.00]
 [0.00 400.00 3.00 2.00 2.00 1.00 0.00 0.00 0.00 50.00]
 [0.00 200.00 2.00 2.00 4.00 0.00 1.00 0.00 0.00 20.00]
 [0.00 150.00 0.00 4.00 1.00 0.00 0.00 1.00 0.00 30.00]
 [0.00 500.00 0.00 4.00 5.00 0.00 0.00 0.00 1.00 80.00]]


In [24]:
bv = [5, 6, 7, 8] #set bv
print('bvs are: \n')
print(bv)
#optimal test and pivot column
r0 = list(A[0])
print(r0)
min_value = min(r0)
if min_value >= 0:
  print('done')
else:
  print('continue')
  pivot_col = r0.index(min_value)
  print('pivot column is ' + str(pivot_col))

#minimum ratio test and pivot row
min_ratio = 10000.0 #big number
pivot_row = 100 #big integer
for i in range(1,n_row):
  if A[i,pivot_col] >0:
    now_ratio = A[i, -1]/A[i, pivot_col]
    if now_ratio < min_ratio:
      min_ratio = now_ratio
      pivot_row = i
print('pivot row is ' + str(pivot_row))
pivot(A, pivot_row,pivot_col)

bvs are: 

[5, 6, 7, 8]
[1.0, -500.0, -6.0, -10.0, -8.0, 0.0, 0.0, 0.0, 0.0, 0.0]
continue
pivot column is 1
pivot row is 2


Current tableau

In [25]:
A

array([[1.00, 249500.00, -6.00, 1990.00, 2492.00, 0.00, 0.00, 0.00,
        500.00, 40000.00],
       [0.00, -199600.00, 3.00, -1598.00, -1998.00, 1.00, 0.00, 0.00,
        -400.00, -31950.00],
       [0.00, 1.00, 0.01, 0.01, 0.02, 0.00, 0.01, 0.00, 0.00, 0.10],
       [0.00, -74850.00, 0.00, -596.00, -749.00, 0.00, 0.00, 1.00,
        -150.00, -11970.00],
       [0.00, -249500.00, 0.00, -1996.00, -2495.00, 0.00, 0.00, 0.00,
        -499.00, -39920.00]])

In [26]:
bv = [1, 5, 7, 8] #set bv
print('bvs are: \n')
print(bv)
#optimal test and pivot column
r0 = list(A[0])
print(r0)
min_value = min(r0)
if min_value >= 0:
  print('done')
else:
  print('continue')
  pivot_col = r0.index(min_value)
  print('pivot column is ' + str(pivot_col))

#minimum ratio test and pivot row
min_ratio = 10000.0 #big number
pivot_row = 100 #big integer
for i in range(1,n_row):
  if A[i,pivot_col] >0:
    now_ratio = A[i, -1]/A[i, pivot_col]
    if now_ratio < min_ratio:
      min_ratio = now_ratio
      pivot_row = i
print('pivot row is ' + str(pivot_row))
pivot(A, pivot_row,pivot_col)

bvs are: 

[1, 5, 7, 8]
[1.0, 249500.0, -6.0, 1990.0, 2492.0, 0.0, 0.0, 0.0, 500.0, 40000.0]
continue
pivot column is 2
pivot row is 1


Current tableau

In [27]:
A

array([[1.00, -1247500.00, -6.00, -9986.00, -12478.00, 0.00, 0.00, 0.00,
        -2494.00, -199520.00],
       [0.00, -66533.33, 1.00, -532.67, -666.00, 0.33, 0.00, 0.00,
        -133.33, -10650.00],
       [0.00, 2496.00, 0.01, 19.97, 24.97, 0.00, 0.01, 0.00, 4.99,
        399.30],
       [0.00, -74850.00, 0.00, -596.00, -749.00, 0.00, 0.00, 1.00,
        -150.00, -11970.00],
       [0.00, -249500.00, 0.00, -1996.00, -2495.00, 0.00, 0.00, 0.00,
        -499.00, -39920.00]])

In [28]:
bv = [1, 3, 5, 8] #set bv
print(bv)
#optimal test and pivot column
r0 = list(A[0])
print(r0)
min_value = min(r0)
if min_value >= 0:
  print('done')
else:
  print('continue')
  pivot_col = r0.index(min_value)
  print('pivot column is ' + str(pivot_col))

#minimum ratio test and pivot row
min_ratio = 10000.0 #big number
pivot_row = 100 #big integer
for i in range(1,n_row):
  if A[i,pivot_col] >0:
    now_ratio = A[i, -1]/A[i, pivot_col]
    if now_ratio < min_ratio:
      min_ratio = now_ratio
      pivot_row = i
print('pivot row is ' + str(pivot_row))
pivot(A, pivot_row,pivot_col)

[1, 3, 5, 8]
[1.0, -1247500.0, -6.0, -9986.0, -12478.0, 0.0, 0.0, 0.0, -2494.0, -199520.0]
continue
pivot column is 1
pivot row is 2


Current tableau

In [29]:
A

array([[1.00, -311252497500.00, -6.00, -2490019986.00, -3112524978.00,
        0.00, 0.00, 0.00, -622504994.00, -49800399520.00],
       [0.00, -16600133200.00, 1.00, -132801066.00, -166001332.67, 0.33,
        0.00, 0.00, -33200266.67, -2656021316.67],
       [0.00, 1.00, 0.00, 0.01, 0.01, 0.00, 0.00, 0.00, 0.00, 0.16],
       [0.00, -18675149850.00, 0.00, -149401196.00, -186751499.00, 0.00,
        0.00, 1.00, -37350300.00, -2988023970.00],
       [0.00, -62250499500.00, 0.00, -498003996.00, -622504995.00, 0.00,
        0.00, 0.00, -124500999.00, -9960079920.00]])

In [30]:
bv = [2, 3, 5, 8] #set bv
print('bvs are: \n')
print(bv)
#optimal test and pivot column
r0 = list(A[0])
print(r0)
min_value = min(r0)
if min_value >= 0:
  print('done')
else:
  print('continue')
  pivot_col = r0.index(min_value)
  print('pivot column is ' + str(pivot_col))


bvs are: 

[2, 3, 5, 8]
[1.0, -311252497500.0, -6.0, -2490019986.0, -3112524978.0, 0.0, 0.0, 0.0, -622504994.0, -49800399520.0]
continue
pivot column is 1


## Conclusion

The optimal solution for the dual problem is 
$$x = (0, 2.5, 7.5, 0), z = 90.$$
Indeed, in the original diet problem, the optimal solution is by eating no brownies, 3 oz ice cream, 1 cola, no pineapples, which yields minimum cost 90.