<a href="https://colab.research.google.com/github/songqsh/foo1/blob/master/src/simplex_diet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simplex method

We are going to illustrate simplex tableau method for linear programing using the following example - WG:
$$\max z = 3 x_1 + 5 x_2$$
s.t.
$$\begin{array}{lll}
x_1 & & \le 4 \\
& 2 x_2 &\le 12 \\
3x_1 & + 2x_2 & \le 18\\
x_1, & x_2 & \ge 0
\end{array}
$$

In [ ]:
# import package
import numpy as np
import numpy.linalg as la
float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

## Matrix in numpy

In [ ]:
# input augmented matrix
AM = np.array([
               [1, -3, -5, 0, 0, 0, 0], 
               [0, 1, 0, 1, 0, 0, 4], 
               [0, 0, 2, 0, 1, 0, 12],
               [0, 3, 2, 0, 0, 1, 18]
               ], dtype = float)
AM # print matrix

array([[1.00, -3.00, -5.00, 0.00, 0.00, 0.00, 0.00],
       [0.00, 1.00, 0.00, 1.00, 0.00, 0.00, 4.00],
       [0.00, 0.00, 2.00, 0.00, 1.00, 0.00, 12.00],
       [0.00, 3.00, 2.00, 0.00, 0.00, 1.00, 18.00]])

## Pivotizing

Pivotizing with $(i,j)$-entry means converting the matrix by multiple EROS so that the resulting matrix has all zeros in $j$-column, but one in $(i,j)$-entry. This is the key step in updating basic feasible solution.

In [ ]:
#pivotize with (i,j)
def pivot(A, i, j):
  A[i] = A[i]/A[i,j] #scale to get one in (i,j)
  n_rows, _ = A.shape
  for k in range(n_rows):
    if k==i:
      continue # skip i-row
    A[k] = A[k] - A[i]*A[k,j] # replacement to get zero
    

In [ ]:
AM

array([[1.00, -3.00, -5.00, 0.00, 0.00, 0.00, 0.00],
       [0.00, 1.00, 0.00, 1.00, 0.00, 0.00, 4.00],
       [0.00, 0.00, 2.00, 0.00, 1.00, 0.00, 12.00],
       [0.00, 3.00, 2.00, 0.00, 0.00, 1.00, 18.00]])

In [ ]:
#test
A = AM.copy()
pivot(A, 2,2)
A

array([[1.00, -3.00, 0.00, 0.00, 2.50, 0.00, 30.00],
       [0.00, 1.00, 0.00, 1.00, 0.00, 0.00, 4.00],
       [0.00, 0.00, 1.00, 0.00, 0.50, 0.00, 6.00],
       [0.00, 3.00, 0.00, 0.00, -1.00, 1.00, 6.00]])

## Simplex tableau

In [ ]:
AM # print original augmented matrix

array([[1.00, -3.00, -5.00, 0.00, 0.00, 0.00, 0.00],
       [0.00, 1.00, 0.00, 1.00, 0.00, 0.00, 4.00],
       [0.00, 0.00, 2.00, 0.00, 1.00, 0.00, 12.00],
       [0.00, 3.00, 2.00, 0.00, 0.00, 1.00, 18.00]])

In [ ]:
pivot(AM, 2, 2)
AM # print

array([[1.00, -3.00, 0.00, 0.00, 2.50, 0.00, 30.00],
       [0.00, 1.00, 0.00, 1.00, 0.00, 0.00, 4.00],
       [0.00, 0.00, 1.00, 0.00, 0.50, 0.00, 6.00],
       [0.00, 3.00, 0.00, 0.00, -1.00, 1.00, 6.00]])

In [ ]:
pivot(AM, 3, 1)
AM #print

array([[1.00, 0.00, 0.00, 0.00, 1.50, 1.00, 36.00],
       [0.00, 0.00, 0.00, 1.00, 0.33, -0.33, 2.00],
       [0.00, 0.00, 1.00, 0.00, 0.50, 0.00, 6.00],
       [0.00, 1.00, 0.00, 0.00, -0.33, 0.33, 2.00]])

Since the 0-row has no negative number, the last entry of the first row is the maximum value, which is 36.