# Simplex method
We will test simplex method using various examples

In [10]:
# import package
import numpy as np
float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})
import warnings
#ignore by message
warnings.filterwarnings("ignore", message="divide by zero encountered in true_divide")

In [11]:
# import self developed simplex method
from simplex import *

# Simplex solver on a standard LP

## An example - WG

We are going to illustrate simplex tableau method for linear programing using the following example - WG:
$$\max z = 3 x_1 + 5 x_2$$
s.t.
$$\begin{array}{lll}
x_1 & & \le 4 \\
& 2 x_2 &\le 12 \\
3x_1 & + 2x_2 & \le 18\\
x_1, & x_2 & \ge 0
\end{array}
$$

## Break down steps

In [12]:
# setup for WG
c = [3., 5]
A = [[1., 0], [0, 2], [3, 2]]
b = [4, 12., 18]

In [13]:
# initial tablet
init_tab = init_tab_standard_lp(A, b, c)
print(init_tab)

[[1.00 -3.00 -5.00 -0.00 -0.00 -0.00 -0.00]
 [0.00 1.00 0.00 1.00 0.00 0.00 4.00]
 [0.00 0.00 2.00 0.00 1.00 0.00 12.00]
 [0.00 3.00 2.00 0.00 0.00 1.00 18.00]]


In [14]:
tab = init_tab.copy()
pivot_n = new_pivot(tab)
if pivot_n != 0:
    pivoting(tab, pivot_n[0], pivot_n[1])
    print(f'new pivot is {pivot_n}')
    print(f'=======================')
    print(tab)

new pivot is (2, 2)
[[1.00 -3.00 0.00 0.00 2.50 0.00 30.00]
 [0.00 1.00 0.00 1.00 0.00 0.00 4.00]
 [0.00 0.00 1.00 0.00 0.50 0.00 6.00]
 [0.00 3.00 0.00 0.00 -1.00 1.00 6.00]]


In [15]:
pivot_n = new_pivot(tab)
if pivot_n != 0:
    pivoting(tab, pivot_n[0], pivot_n[1])
    print(f'new pivot is {pivot_n}')
    print(f'=======================')
    print(tab)

new pivot is (3, 1)
[[1.00 0.00 0.00 0.00 1.50 1.00 36.00]
 [0.00 0.00 0.00 1.00 0.33 -0.33 2.00]
 [0.00 0.00 1.00 0.00 0.50 0.00 6.00]
 [0.00 1.00 0.00 0.00 -0.33 0.33 2.00]]


In [16]:
pivot_n = new_pivot(tab)
if pivot_n != 0:
    pivoting(tab, pivot_n[0], pivot_n[1])
    print(f'new pivot is {pivot_n}')
    print(f'=======================')
    print(tab)

pass the optimal test
optimal value is 36.0
The final tableau is 
      0    1    2    3         4         5     6
0  1.0  0.0  0.0  0.0  1.500000  1.000000  36.0
1  0.0  0.0  0.0  1.0  0.333333 -0.333333   2.0
2  0.0  0.0  1.0  0.0  0.500000  0.000000   6.0
3  0.0  1.0  0.0  0.0 -0.333333  0.333333   2.0


## One-shot solver

In [17]:
simplex_solver(init_tab, display=1)

3 constraints and 5 variables
initial tableau is:
[[1.00 -3.00 -5.00 -0.00 -0.00 -0.00 -0.00]
 [0.00 1.00 0.00 1.00 0.00 0.00 4.00]
 [0.00 0.00 2.00 0.00 1.00 0.00 12.00]
 [0.00 3.00 2.00 0.00 0.00 1.00 18.00]]
new pivot is (2, 2)
[[1.00 -3.00 0.00 0.00 2.50 0.00 30.00]
 [0.00 1.00 0.00 1.00 0.00 0.00 4.00]
 [0.00 0.00 1.00 0.00 0.50 0.00 6.00]
 [0.00 3.00 0.00 0.00 -1.00 1.00 6.00]]
new pivot is (3, 1)
[[1.00 0.00 0.00 0.00 1.50 1.00 36.00]
 [0.00 0.00 0.00 1.00 0.33 -0.33 2.00]
 [0.00 0.00 1.00 0.00 0.50 0.00 6.00]
 [0.00 1.00 0.00 0.00 -0.33 0.33 2.00]]
pass the optimal test
optimal value is 36.0
The final tableau is 
      0    1    2    3         4         5     6
0  1.0  0.0  0.0  0.0  1.500000  1.000000  36.0
1  0.0  0.0  0.0  1.0  0.333333 -0.333333   2.0
2  0.0  0.0  1.0  0.0  0.500000  0.000000   6.0
3  0.0  1.0  0.0  0.0 -0.333333  0.333333   2.0
