<a href="https://colab.research.google.com/github/songqsh/foo1/blob/master/src/transport_bfs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transport problem
From Section 8.1



In [3]:
# import packages
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)
import itertools

In [18]:

A = np.array([[1., 1., 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
              [0., 0., 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
              [0., 0., 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0], 
              [1., 0., 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
              [0., 1., 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
              [0., 0., 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
              [0., 0., 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]])
b = np.array([75., 125, 100, 80, 65, 70, 85])

M=1000
c = np.array([-464., -513, -654, -867, -352, -416,
              -690, -791, -995, -682, -388, -685, 
              -M, -M, -M, -M, -M, -M, -M])
m, n = A.shape
print(f'coefficient matrix is \n {A}')
print(f'right hand side vector is \n {b}')
print(f'coefficient of objective function is \n {c}')
print(f'n is {n} and m is {m}')

coefficient matrix is 
 [[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]]
right hand side vector is 
 [ 75. 125. 100.  80.  65.  70.  85.]
coefficient of objective function is 
 [ -464.  -513.  -654.  -867.  -352.  -416.  -690.  -791.  -995.  -682.
  -388.  -685. -1000. -1000. -1000. -1000. -1000. -1000. -1000.]
n is 19 and m is 7


In [27]:
a_list = list(range(n))

bv_list = itertools.combinations(a_list,m)
n_bfs = 0 # number of bfs recording
opt_soln = []
opt_value = -1000000
for bv in bv_list:
  try:
    bs = la.solve(A[:,bv], b)
    #print(f'bv is {bv} and bs is {bs}')
    
    if min(bs) >= 0:
      z=0
      for i in range(m):
        z = z + c[bv[i]]*bs[i]
      #print(f'...it is bfs and z-value is {z}')
      n_bfs += 1
      if z>opt_value:
        opt_value = z
        opt_soln = bs

  except:
    pass
    #print(f'bv is {bv} and it is singular')

print(f'number of bfs is {n_bfs}')
print(f'optimal value is {opt_value}')
print(f'optimal solution is {opt_soln}')

number of bfs is 1859
optimal value is -152535.0
optimal solution is [20. 55. 80. 45. 70. 30. -0.]


In [26]:
import math
n_bs = math.factorial(19)/math.factorial(7)/math.factorial(12)
print(f'number of basic solutions (including singluar case) is {n_bs}')

number of basic solutions (including singluar case) is 50388.0
